language: java

sudo: false

jdk:
- oraclejdk8

os:
- linux

notifications:
  on_success: change
  on_failure: always
  template:
  - "%{repository} (%{branch}:%{commit} by %{author}): %{message} (%{build_url})"
